import Testing
import Foundation
@testable import FluxQModels

@Suite("Message Tests")
struct MessageTests {

    @Test("Initialization with all parameters")
    func initWithAllParameters() {
        let date = Date(timeIntervalSince1970: 1700000000)
        let msgId = UUID(uuidString: "00000000-0000-0000-0000-000000000001")!
        let convId = UUID(uuidString: "00000000-0000-0000-0000-000000000010")!
        let senderId = UUID(uuidString: "00000000-0000-0000-0000-000000000020")!
        let message = Message(
            id: msgId,
            conversationID: convId,
            senderID: senderId,
            content: "Hello, World!",
            timestamp: date,
            status: .delivered,
            isEncrypted: true
        )

        #expect(message.id == msgId)
        #expect(message.conversationID == convId)
        #expect(message.senderID == senderId)
        #expect(message.content == "Hello, World!")
        #expect(message.timestamp == date)
        #expect(message.status == .delivered)
        #expect(message.isEncrypted == true)
    }

    @Test("Default values are applied correctly")
    func defaultValues() {
        let convId = UUID()
        let senderId = UUID()
        let before = Date()
        let message = Message(
            conversationID: convId,
            senderID: senderId,
            content: "Test"
        )
        let after = Date()

        #expect(message.status == .sending)
        #expect(message.isEncrypted == false)
        #expect(message.timestamp >= before)
        #expect(message.timestamp <= after)
    }

    @Test("ID is auto-generated as UUID")
    func autoGeneratedID() {
        let convId = UUID()
        let senderId = UUID()
        let msg1 = Message(conversationID: convId, senderID: senderId, content: "a")
        let msg2 = Message(conversationID: convId, senderID: senderId, content: "b")

        #expect(msg1.id != msg2.id)
    }

    @Test("Timestamp records correctly")
    func timestampRecording() {
        let specificDate = Date(timeIntervalSince1970: 1609459200) // 2021-01-01
        let message = Message(
            conversationID: UUID(),
            senderID: UUID(),
            content: "New Year",
            timestamp: specificDate
        )

        #expect(message.timestamp == specificDate)
        #expect(message.timestamp.timeIntervalSince1970 == 1609459200)
    }

    @Test("SenderID and conversationID stored correctly")
    func senderAndConversationIDs() {
        let convId = UUID(uuidString: "00000000-0000-0000-0000-000000000030")!
        let senderId = UUID(uuidString: "00000000-0000-0000-0000-000000000040")!
        let message = Message(
            conversationID: convId,
            senderID: senderId,
            content: "Test"
        )

        #expect(message.senderID == senderId)
        #expect(message.conversationID == convId)
    }

    @Test("Content supports empty string")
    func emptyContent() {
        let message = Message(
            conversationID: UUID(),
            senderID: UUID(),
            content: ""
        )

        #expect(message.content == "")
        #expect(message.content.isEmpty)
    }

    @Test("Content supports long text")
    func longContent() {
        let longText = String(repeating: "A", count: 10_000)
        let message = Message(
            conversationID: UUID(),
            senderID: UUID(),
            content: longText
        )

        #expect(message.content == longText)
        #expect(message.content.count == 10_000)
    }

    @Test("Content supports Unicode and emoji")
    func unicodeAndEmojiContent() {
        let unicodeContent = "Hello \u{1F600} 你好世界 こんにちは 🎉🚀"
        let message = Message(
            conversationID: UUID(),
            senderID: UUID(),
            content: unicodeContent
        )

        #expect(message.content == unicodeContent)
        #expect(message.content.contains("🎉"))
        #expect(message.content.contains("你好世界"))
    }

    @Test("All MessageStatus values can be assigned")
    func allStatusValues() {
        let statuses: [MessageStatus] = [.sending, .sent, .delivered, .read, .failed]
        for status in statuses {
            let message = Message(
                conversationID: UUID(),
                senderID: UUID(),
                content: "Test",
                status: status
            )
            #expect(message.status == status)
        }
    }

    @Test("isEncrypted flag works correctly")
    func encryptedFlag() {
        let encrypted = Message(
            conversationID: UUID(),
            senderID: UUID(),
            content: "Secret",
            isEncrypted: true
        )
        let unencrypted = Message(
            conversationID: UUID(),
            senderID: UUID(),
            content: "Public",
            isEncrypted: false
        )

        #expect(encrypted.isEncrypted == true)
        #expect(unencrypted.isEncrypted == false)
    }
}
